name: FamiLib
version: '${project.version}'
main: me.familib.FamiLib
api-version: 1.19
softdepend: [ ProtocolLib, HolographicDisplays ]
authors: [ Fami6Xx ]
description: Library for my (Fami6Xx) current and future plugins
website: https://github.com/Fami6Xx
